### ISSUE TITLE
Vue 2.0

### ISSUE THREAD

**Issue by ryandeussing** [paulpflug/vue-mixins#1]
Hi, I'm attempting to use `vue-comps/vue-scrollfire` and while it looks like upgrading it to 2.0 might be as easy as changing lifecycle hooks,`vue-mixins` is pegged to `"vue": "^1.0.26"`.

Any plans to get your awesome mixins and components 2.0 compatible? Thanks

**Comment by paulpflug** [comment]
hey,

I just released [vue-scrollfire@2](https://github.com/vue-comps/vue-scrollfire). I will make any of my components 2.0 compatible, but currently only on request - So I see what is needed most ;)
vue-mixins currently is for both vue@1 and vue@2
Most mixins are inherently compatible to both versions, but for example `isOpened` exists as `isOpened` and `isOpened2`.
The devDependency of `vue` is only used for unit testing..

**Comment by ryandeussing** [comment]
Danke sehr!
